# Generated by Django 3.1.1 on 2020-11-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('city', models.CharField(max_length=30)),
                ('ownership', models.CharField(max_length=50)),
                ('admissionCapacit', models.CharField(max_length=10)),
                ('hospitalBeds', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=30)),
            ],
        ),
    ]
