# Generated by Django 3.1.1 on 2020-11-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='admissionCapacit',
            new_name='admissionCapacity',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='hospitalBeds',
            new_name='covidBeds',
        ),
    ]
